# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_EEG.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(845, 614)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./src/Brain-Games.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.Directory_Line = QtGui.QLineEdit(self.centralwidget)
        self.Directory_Line.setEnabled(True)
        self.Directory_Line.setGeometry(QtCore.QRect(250, 410, 431, 21))
        self.Directory_Line.setMouseTracking(True)
        self.Directory_Line.setReadOnly(True)
        self.Directory_Line.setObjectName(_fromUtf8("Directory_Line"))
        self.OpenDialog = QtGui.QPushButton(self.centralwidget)
        self.OpenDialog.setGeometry(QtCore.QRect(680, 410, 31, 21))
        self.OpenDialog.setObjectName(_fromUtf8("OpenDialog"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 410, 131, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.Training_Box = QtGui.QGroupBox(self.centralwidget)
        self.Training_Box.setGeometry(QtCore.QRect(120, 430, 271, 151))
        self.Training_Box.setObjectName(_fromUtf8("Training_Box"))
        self.label_2 = QtGui.QLabel(self.Training_Box)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Total_Training = QtGui.QSpinBox(self.Training_Box)
        self.Total_Training.setGeometry(QtCore.QRect(20, 40, 71, 22))
        self.Total_Training.setMinimum(1)
        self.Total_Training.setMaximum(10000)
        self.Total_Training.setObjectName(_fromUtf8("Total_Training"))
        self.Total_Testing = QtGui.QSpinBox(self.Training_Box)
        self.Total_Testing.setGeometry(QtCore.QRect(200, 40, 61, 22))
        self.Total_Testing.setMaximum(100000)
        self.Total_Testing.setObjectName(_fromUtf8("Total_Testing"))
        self.label_3 = QtGui.QLabel(self.Training_Box)
        self.label_3.setGeometry(QtCore.QRect(180, 20, 91, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.TrainingData = QtGui.QPushButton(self.Training_Box)
        self.TrainingData.setGeometry(QtCore.QRect(100, 40, 91, 31))
        self.TrainingData.setObjectName(_fromUtf8("TrainingData"))
        self.AmbilData = QtGui.QPushButton(self.Training_Box)
        self.AmbilData.setGeometry(QtCore.QRect(20, 80, 71, 31))
        self.AmbilData.setObjectName(_fromUtf8("AmbilData"))
        self.AddData = QtGui.QPushButton(self.Training_Box)
        self.AddData.setGeometry(QtCore.QRect(120, 80, 41, 31))
        self.AddData.setObjectName(_fromUtf8("AddData"))
        self.DeleteData = QtGui.QPushButton(self.Training_Box)
        self.DeleteData.setGeometry(QtCore.QRect(190, 80, 71, 31))
        self.DeleteData.setObjectName(_fromUtf8("DeleteData"))
        self.label_12 = QtGui.QLabel(self.Training_Box)
        self.label_12.setGeometry(QtCore.QRect(30, 120, 111, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.error = QtGui.QDoubleSpinBox(self.Training_Box)
        self.error.setGeometry(QtCore.QRect(160, 120, 81, 22))
        self.error.setDecimals(8)
        self.error.setObjectName(_fromUtf8("error"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 50, 46, 13))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.status_hasil_Training = QtGui.QLabel(self.centralwidget)
        self.status_hasil_Training.setGeometry(QtCore.QRect(70, 50, 211, 16))
        self.status_hasil_Training.setObjectName(_fromUtf8("status_hasil_Training"))
        self.CEKROBOT_Box = QtGui.QGroupBox(self.centralwidget)
        self.CEKROBOT_Box.setGeometry(QtCore.QRect(400, 430, 151, 151))
        self.CEKROBOT_Box.setObjectName(_fromUtf8("CEKROBOT_Box"))
        self.Maju_Cek = QtGui.QPushButton(self.CEKROBOT_Box)
        self.Maju_Cek.setGeometry(QtCore.QRect(10, 20, 61, 23))
        self.Maju_Cek.setObjectName(_fromUtf8("Maju_Cek"))
        self.Berhenti_Cek = QtGui.QPushButton(self.CEKROBOT_Box)
        self.Berhenti_Cek.setGeometry(QtCore.QRect(80, 20, 61, 23))
        self.Berhenti_Cek.setObjectName(_fromUtf8("Berhenti_Cek"))
        self.Mundur_Cek = QtGui.QPushButton(self.CEKROBOT_Box)
        self.Mundur_Cek.setGeometry(QtCore.QRect(40, 50, 75, 23))
        self.Mundur_Cek.setObjectName(_fromUtf8("Mundur_Cek"))
        self.COM = QtGui.QComboBox(self.CEKROBOT_Box)
        self.COM.setGeometry(QtCore.QRect(30, 120, 91, 22))
        self.COM.setObjectName(_fromUtf8("COM"))
        self.label_14 = QtGui.QLabel(self.CEKROBOT_Box)
        self.label_14.setGeometry(QtCore.QRect(50, 80, 61, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.Integrasi_Box = QtGui.QGroupBox(self.centralwidget)
        self.Integrasi_Box.setGeometry(QtCore.QRect(560, 430, 161, 151))
        self.Integrasi_Box.setObjectName(_fromUtf8("Integrasi_Box"))
        self.Run_Integrasi = QtGui.QPushButton(self.Integrasi_Box)
        self.Run_Integrasi.setGeometry(QtCore.QRect(40, 30, 75, 23))
        self.Run_Integrasi.setObjectName(_fromUtf8("Run_Integrasi"))
        self.Stop_Integrasi = QtGui.QPushButton(self.Integrasi_Box)
        self.Stop_Integrasi.setGeometry(QtCore.QRect(40, 100, 75, 23))
        self.Stop_Integrasi.setObjectName(_fromUtf8("Stop_Integrasi"))
        self.PilihAktifitas_Box = QtGui.QGroupBox(self.centralwidget)
        self.PilihAktifitas_Box.setGeometry(QtCore.QRect(90, 0, 471, 41))
        self.PilihAktifitas_Box.setObjectName(_fromUtf8("PilihAktifitas_Box"))
        self.radio_Training = QtGui.QRadioButton(self.PilihAktifitas_Box)
        self.radio_Training.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.radio_Training.setObjectName(_fromUtf8("radio_Training"))
        self.radio_CekRobot = QtGui.QRadioButton(self.PilihAktifitas_Box)
        self.radio_CekRobot.setGeometry(QtCore.QRect(120, 10, 81, 21))
        self.radio_CekRobot.setObjectName(_fromUtf8("radio_CekRobot"))
        self.radio_Integrasi = QtGui.QRadioButton(self.PilihAktifitas_Box)
        self.radio_Integrasi.setGeometry(QtCore.QRect(210, 10, 82, 21))
        self.radio_Integrasi.setObjectName(_fromUtf8("radio_Integrasi"))
        self.EKSEKUSI = QtGui.QPushButton(self.PilihAktifitas_Box)
        self.EKSEKUSI.setGeometry(QtCore.QRect(300, 10, 75, 23))
        self.EKSEKUSI.setObjectName(_fromUtf8("EKSEKUSI"))
        self.RESET = QtGui.QPushButton(self.PilihAktifitas_Box)
        self.RESET.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.RESET.setObjectName(_fromUtf8("RESET"))
        self.Table_Training = QtGui.QTableWidget(self.centralwidget)
        self.Table_Training.setEnabled(True)
        self.Table_Training.setGeometry(QtCore.QRect(20, 70, 431, 141))
        self.Table_Training.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.Table_Training.setShowGrid(True)
        self.Table_Training.setRowCount(1)
        self.Table_Training.setColumnCount(26)
        self.Table_Training.setObjectName(_fromUtf8("Table_Training"))
        self.Table_Training.horizontalHeader().setVisible(True)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(590, 0, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.time = QtGui.QSpinBox(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(600, 20, 51, 22))
        self.time.setObjectName(_fromUtf8("time"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(660, 20, 46, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(350, 50, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nyala"))
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.Table_Testing = QtGui.QTableWidget(self.centralwidget)
        self.Table_Testing.setEnabled(True)
        self.Table_Testing.setGeometry(QtCore.QRect(20, 260, 431, 141))
        self.Table_Testing.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.Table_Testing.setShowGrid(True)
        self.Table_Testing.setRowCount(1)
        self.Table_Testing.setColumnCount(26)
        self.Table_Testing.setObjectName(_fromUtf8("Table_Testing"))
        self.Table_Testing.horizontalHeader().setVisible(True)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(360, 230, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nyala"))
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 240, 46, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.status_hasil_Testing = QtGui.QLabel(self.centralwidget)
        self.status_hasil_Testing.setGeometry(QtCore.QRect(70, 240, 211, 16))
        self.status_hasil_Testing.setObjectName(_fromUtf8("status_hasil_Testing"))
        self.Table_Target_Training = QtGui.QTableWidget(self.centralwidget)
        self.Table_Target_Training.setEnabled(True)
        self.Table_Target_Training.setGeometry(QtCore.QRect(500, 70, 321, 141))
        self.Table_Target_Training.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.Table_Target_Training.setShowGrid(True)
        self.Table_Target_Training.setRowCount(1)
        self.Table_Target_Training.setColumnCount(3)
        self.Table_Target_Training.setObjectName(_fromUtf8("Table_Target_Training"))
        self.Table_Target_Training.horizontalHeader().setVisible(True)
        self.Table_Target_Testing = QtGui.QTableWidget(self.centralwidget)
        self.Table_Target_Testing.setEnabled(True)
        self.Table_Target_Testing.setGeometry(QtCore.QRect(500, 260, 321, 141))
        self.Table_Target_Testing.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.Table_Target_Testing.setShowGrid(True)
        self.Table_Target_Testing.setRowCount(1)
        self.Table_Target_Testing.setColumnCount(3)
        self.Table_Target_Testing.setObjectName(_fromUtf8("Table_Target_Testing"))
        self.Table_Target_Testing.horizontalHeader().setVisible(True)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(590, 230, 171, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nyala"))
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(580, 40, 171, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nyala"))
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.CEK = QtGui.QPushButton(self.centralwidget)
        self.CEK.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.CEK.setObjectName(_fromUtf8("CEK"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 0, 61, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.EXIT = QtGui.QPushButton(self.centralwidget)
        self.EXIT.setGeometry(QtCore.QRect(740, 20, 75, 23))
        self.EXIT.setObjectName(_fromUtf8("EXIT"))
        self.Load_testing = QtGui.QPushButton(self.centralwidget)
        self.Load_testing.setGeometry(QtCore.QRect(300, 240, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nyala"))
        self.Load_testing.setFont(font)
        self.Load_testing.setObjectName(_fromUtf8("Load_testing"))
        self.Load_training = QtGui.QPushButton(self.centralwidget)
        self.Load_training.setGeometry(QtCore.QRect(290, 50, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nyala"))
        self.Load_training.setFont(font)
        self.Load_training.setObjectName(_fromUtf8("Load_training"))
        self.Load_T_training = QtGui.QPushButton(self.centralwidget)
        self.Load_T_training.setGeometry(QtCore.QRect(770, 50, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nyala"))
        self.Load_T_training.setFont(font)
        self.Load_T_training.setObjectName(_fromUtf8("Load_T_training"))
        self.Load_T_testing = QtGui.QPushButton(self.centralwidget)
        self.Load_T_testing.setGeometry(QtCore.QRect(770, 240, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nyala"))
        self.Load_T_testing.setFont(font)
        self.Load_T_testing.setObjectName(_fromUtf8("Load_T_testing"))
        self.save_training = QtGui.QPushButton(self.centralwidget)
        self.save_training.setGeometry(QtCore.QRect(230, 50, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nyala"))
        self.save_training.setFont(font)
        self.save_training.setObjectName(_fromUtf8("save_training"))
        self.save_testing = QtGui.QPushButton(self.centralwidget)
        self.save_testing.setGeometry(QtCore.QRect(240, 240, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nyala"))
        self.save_testing.setFont(font)
        self.save_testing.setObjectName(_fromUtf8("save_testing"))
        self.save_T_training = QtGui.QPushButton(self.centralwidget)
        self.save_T_training.setGeometry(QtCore.QRect(500, 50, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nyala"))
        self.save_T_training.setFont(font)
        self.save_T_training.setObjectName(_fromUtf8("save_T_training"))
        self.save_T_testing = QtGui.QPushButton(self.centralwidget)
        self.save_T_testing.setGeometry(QtCore.QRect(500, 240, 51, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nyala"))
        self.save_T_testing.setFont(font)
        self.save_T_testing.setObjectName(_fromUtf8("save_T_testing"))
        self.status_hasil_Testing.raise_()
        self.Directory_Line.raise_()
        self.OpenDialog.raise_()
        self.label.raise_()
        self.Training_Box.raise_()
        self.label_4.raise_()
        self.status_hasil_Training.raise_()
        self.CEKROBOT_Box.raise_()
        self.Integrasi_Box.raise_()
        self.PilihAktifitas_Box.raise_()
        self.Table_Training.raise_()
        self.label_5.raise_()
        self.time.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.Table_Testing.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.Table_Target_Training.raise_()
        self.Table_Target_Testing.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.CEK.raise_()
        self.label_13.raise_()
        self.EXIT.raise_()
        self.Load_testing.raise_()
        self.Load_training.raise_()
        self.Load_T_training.raise_()
        self.Load_T_testing.raise_()
        self.save_training.raise_()
        self.save_testing.raise_()
        self.save_T_training.raise_()
        self.save_T_testing.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Electroencephalograph", None))
        self.OpenDialog.setText(_translate("MainWindow", "...", None))
        self.label.setText(_translate("MainWindow", "Select Directory Save ELM", None))
        self.Training_Box.setTitle(_translate("MainWindow", "TRAINING DATA", None))
        self.label_2.setText(_translate("MainWindow", "Total Data Training", None))
        self.label_3.setText(_translate("MainWindow", "Total Data Testing", None))
        self.TrainingData.setText(_translate("MainWindow", "TRAINING DATA", None))
        self.AmbilData.setText(_translate("MainWindow", "AMBIL DATA", None))
        self.AddData.setText(_translate("MainWindow", "ADD", None))
        self.DeleteData.setText(_translate("MainWindow", "DELETE", None))
        self.label_12.setText(_translate("MainWindow", "Error yang di inginkan", None))
        self.label_4.setText(_translate("MainWindow", "STATUS :", None))
        self.status_hasil_Training.setText(_translate("MainWindow", "READY", None))
        self.CEKROBOT_Box.setTitle(_translate("MainWindow", "CEK ROBOT", None))
        self.Maju_Cek.setText(_translate("MainWindow", "MAJU", None))
        self.Berhenti_Cek.setText(_translate("MainWindow", "BERHENTI", None))
        self.Mundur_Cek.setText(_translate("MainWindow", "MUNDUR", None))
        self.label_14.setText(_translate("MainWindow", "Select COM", None))
        self.Integrasi_Box.setTitle(_translate("MainWindow", "Integrasi", None))
        self.Run_Integrasi.setText(_translate("MainWindow", "RUN", None))
        self.Stop_Integrasi.setText(_translate("MainWindow", "STOP", None))
        self.PilihAktifitas_Box.setTitle(_translate("MainWindow", "PILIH AKTIFITAS", None))
        self.radio_Training.setText(_translate("MainWindow", "TRAINING DATA", None))
        self.radio_CekRobot.setText(_translate("MainWindow", "CEK ROBOT", None))
        self.radio_Integrasi.setText(_translate("MainWindow", "INTEGRASI", None))
        self.EKSEKUSI.setText(_translate("MainWindow", "EKSEKUSI", None))
        self.RESET.setText(_translate("MainWindow", "RESTART", None))
        self.label_5.setText(_translate("MainWindow", "Waktu Pengambilan Data", None))
        self.label_6.setText(_translate("MainWindow", "Seconds", None))
        self.label_7.setText(_translate("MainWindow", "Tabel Training", None))
        self.label_8.setText(_translate("MainWindow", "Tabel Testing", None))
        self.label_9.setText(_translate("MainWindow", "STATUS :", None))
        self.status_hasil_Testing.setText(_translate("MainWindow", "READY", None))
        self.label_10.setText(_translate("MainWindow", "Tabel Targeting Testing", None))
        self.label_11.setText(_translate("MainWindow", "Tabel Targeting Training", None))
        self.CEK.setText(_translate("MainWindow", "CEK", None))
        self.label_13.setText(_translate("MainWindow", "Cek Emotiv", None))
        self.EXIT.setText(_translate("MainWindow", "EXIT", None))
        self.Load_testing.setText(_translate("MainWindow", "LOAD", None))
        self.Load_training.setText(_translate("MainWindow", "LOAD", None))
        self.Load_T_training.setText(_translate("MainWindow", "LOAD", None))
        self.Load_T_testing.setText(_translate("MainWindow", "LOAD", None))
        self.save_training.setText(_translate("MainWindow", "SAVE", None))
        self.save_testing.setText(_translate("MainWindow", "SAVE", None))
        self.save_T_training.setText(_translate("MainWindow", "SAVE", None))
        self.save_T_testing.setText(_translate("MainWindow", "SAVE", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

